# Generated by Django 4.0.2 on 2022-03-30 13:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='publish',
            name='author',
        ),
        migrations.AddField(
            model_name='publish',
            name='author',
            field=models.ManyToManyField(to='core.Author'),
        ),
    ]
