# Generated by Django 4.0.2 on 2022-03-30 16:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.models.files_path, verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.files_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
